services:
  backend1:
    build:
      context: ./backend
    environment:
      PORT: 8000
      SERVER_NAME: backend1

  backend2:
    build:
      context: ./backend
    environment:
      PORT: 8000
      SERVER_NAME: backend2

  backend3:
    build:
      context: ./backend
    environment:
      PORT: 8000
      SERVER_NAME: backend3-backup

  haproxy:
    image: haproxy:2.9-alpine
    depends_on:
      - backend1
      - backend2
      - backend3
    ports:
      - "8081:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro